---
abstract: 'A media gallery'
author:
  - 'Johannes ''fish' Ziemke <fish-code@freigeist.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CGI-Application-Phosy
no_index:
  directory:
    - share
    - share
    - inc
    - examples
    - examples
requires:
  CGI::Application: 0
  CGI::Application::Plugin::Config::Simple: 0
  CGI::Application::Plugin::HTCompiled: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  Image::ExifTool: 0
  Image::Magick: 0
  MIME::Types: 0
version: 0.01
